###heron
#Enter a: …
#Enter b: …
#Enter c: …
#Triangle area: …
#Triangle circumference: …

a=int(input("enter a: "))
b=int(input("enter b: "))
c=int(input("enter c: "))
s=(a+b+c)/2
heron=(s*(s-a)*(s-b)*(s-c))**(1/2)
circumference=a+b+c
print(f"area= {heron}, circumference={circumference}")
